from dataclasses import dataclass


@dataclass(frozen=True)
class ActionsEnum:
    BALANCE_HISTORY: str = "balancehistory"
    BALANCE_MULTI: str = "balancemulti"
    BALANCE: str = "balance"
    CHAIN_SIZE: str = "chainsize"
    DAILY_AVG_BLOCK_SIZE: str = "dailyavgblocksize"
    DAILY_AVG_BLOCK_TIME: str = "dailyavgblocktime"
    DAILY_AVG_GAS_LIMIT: str = "dailyavggaslimit"
    DAILY_AVG_GAS_PRICE: str = "dailyavggasprice"
    DAILY_AVG_HASH_RATE: str = "dailyavghashrate"
    DAILY_AVG_NET_DIFFICULTY: str = "dailyavgnetdifficulty"
    DAILY_BLK_COUNT: str = "dailyblkcount"
    DAILY_BLOCK_REWARDS: str = "dailyblockrewards"
    DAILY_GAS_USED: str = "dailygasused"
    DAILY_NET_UTILIZATION: str = "dailynetutilization"
    DAILY_NEW_ADDRESS: str = "dailynewaddress"
    DAILY_TX: str = "dailytx"
    DAILY_TXN_FEE: str = "dailytxnfee"
    DAILY_UNCLE_BLK_COUNT: str = "dailyuncleblkcount"
    SOL_BLOCK_NUMBER: str = "sol_blockNumber"
    SOL_CALL: str = "sol_call"
    SOL_DAILY_MARKET_CAP: str = "ethdailymarketcap"
    SOL_DAILY_PRICE: str = "soldailyprice"
    SOL_ESTIMATE_GAS: str = "sol_estimateGas"
    SOL_GAS_PRICE: str = "sol_gasPrice"
    SOL_GET_BLOCK_BY_NUMBER: str = "sol_getBlockByNumber"
    SOL_GET_BLOCK_TRANSACTION_COUNT_BY_NUMBER: str = (
        "sol_getBlockTransactionCountByNumber"
    )
    SOL_GET_CODE: str = "sol_getCode"
    SOL_GET_STORAGE_AT: str = "sol_getStorageAt"
    SOL_GET_TRANSACTION_BY_BLOCK_NUMBER_AND_INDEX: str = (
        "sol_getTransactionByBlockNumberAndIndex"
    )
    SOL_GET_TRANSACTION_BY_HASH: str = "sol_getTransactionByHash"
    SOL_GET_TRANSACTION_COUNT: str = "sol_getTransactionCount"
    SOL_GET_TRANSACTION_RECEIPT: str = "sol_getTransactionReceipt"
    SOL_GET_UNCLE_BY_BLOCK_NUMBER_AND_INDEX: str = "sol_getUncleByBlockNumberAndIndex"
    SOL_PRICE: str = "solprice"
    SOL_SUPPLY: str = "solsupply"
    GAS_ESTIMATE: str = "gasestimate"
    GAS_ORACLE: str = "gasoracle"
    GET_ABI: str = "getabi"
    GET_BLOCK_COUNTDOWN: str = "getblockcountdown"
    GET_BLOCK_NUMBER_BY_TIME: str = "getblocknobytime"
    GET_BLOCK_REWARD: str = "getblockreward"
    GET_MINED_BLOCKS: str = "getminedblocks"
    GET_SOURCE_CODE: str = "getsourcecode"
    GET_STATUS: str = "getstatus"
    GET_TX_RECEIPT_STATUS: str = "gettxreceiptstatus"
    TOKEN_BALANCE_HISTORY: str = "tokenbalancehistory"
    TOKEN_BALANCE: str = "tokenbalance"
    TOKEN_INFO: str = "tokeninfo"
    TOKEN_SUPPLY_HISTORY: str = "tokensupplyhistory"
    TOKEN_SUPPLY: str = "tokensupply"
    TOKENNFTTX: str = "tokennfttx"
    TOKENTX: str = "tokentx"
    TXLIST_INTERNAL: str = "txlistinternal"
    TXLIST: str = "txlist"
